trigger:
- main

pool:
  name: Default

variables:
  name: bicepArtifactName
  value: bicep

jobs:
- job: Build
  workspace:
    clean: all    
  displayName: 'Publish bicep to artifact'  
  steps:
  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: '$(System.DefaultWorkingDirectory)/azdo/biceps'
      artifactName: $(bicepArtifactName)
    displayName: 'publish biceps to Azure DevOps - $(bicepArtifactName)'          
- deployment: Deploy
  environment: platformsre-test
  dependsOn: Build 
  displayName: 'Deploy To Azure'
  strategy:
    runOnce:
      deploy:
        steps:
        - task: AzureResourceManagerTemplateDeployment@3
          displayName: 'Deploy Biceps files'        
          inputs:
            deploymentScope: 'Resource Group'
            azureResourceManagerConnection: proton-account-svc-conn-01
            subscriptionId: 'd7ab4684-6d5e-4bd3-a6c5-93965b7c0cdc'
            action: 'Create Or Update Resource Group'
            resourceGroupName: 'platformsre-rg'
            location: 'swedencentral'
            templateLocation: 'Linked artifact'
            csmFile: '$(Build.ArtifactStagingDirectory)/$(bicepArtifactName)/main.bicep'
            deploymentMode: 'Incremental'


