trigger:
- main

pool:
  name: Default

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo test newly created self-hosted buildagent
  displayName: 'Run a multi-line script'

